### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by TERNION-1121** [Legendary3995/Collision-In-2-Dimension#2]
Firstly when entering the mass in float, it throws error.

Secondly the images must be present in the repository, then only the GUI would function; elsewise, again it'd throw error.
Please fix it

```
Traceback (most recent call last):
  File "c:\Python_Programming\School Programs\lak-collision.py", line 20, in <module>
    icon = pygame.image.load('images/icon.png')
FileNotFoundError: No file 'images/icon.png' found in working directory 'C:\Python_Programming'.
PS C:\Python_Programming>
 ```

![image](https://user-images.githubusercontent.com/97667653/177155416-025334dc-07ea-4bd6-a670-494656ece433.png)

**Comment by mythikosium** [comment]
Problem Fixed

This error was there because the files that I mentioned to load in the program weren't found at the path mentioned.

**Comment by TERNION-1121** [comment]
![image](https://user-images.githubusercontent.com/97667653/177198699-ac5c8a33-8872-4c31-8f20-383f93cbcf97.png)
![image](https://user-images.githubusercontent.com/97667653/177198696-f00645ed-51f5-4cc0-a741-28c4b3f7ac60.png)
Still giving error ;-;

**Comment by mythikosium** [comment]
Issue resolved
